### ISSUE TITLE
Inconsistent API resource routes

### ISSUE THREAD

**Issue by lotzk** [ExplorViz/explorviz-backend#118]
There are some ambiguities and inconsistencies to our REST API:

- The User-Service provides the collection of all users at the `/users/` route. Naturally, a single user is addressed by its ID as follows `/users/<user-id>/`. However, the route to create batches of users is `/users/batch/`. 

- The collection of all available settings can be retrieved with a GET request to `/settings/info/`. However, the `info` suffix provides no meaning at all and should be removed from the URI.

- The user preferences can be fetched from `/users/<user-id>/settings/preferences` where again the `settings` does not provide any meaning and should be removed.

**Comment by Alexander-Krause** [comment]
You are thinking about

- `/users/batch/` -> `/batch`
- `/settings/info/` -> `/info`
- `/users/<user-id>/settings/preferences` -> `/users/<user-id>/preferences`

right?

**Comment by lotzk** [comment]
I'm not sure about the first one because I think the URI should somehow reflect the relation to the user model. For the settings I think `/settings/` would be the better option since it is a little more expressive.

**Comment by Alexander-Krause** [comment]
I was stupid or tired. Of course I meant `/settings/info/ -> /settings/`. 

About the first one (this does not really solve the issue, but is nice to know imho): https://stackoverflow.com/questions/20951419/what-are-best-practices-for-rest-nested-resources

So, we have to figure out if it is good to allow subresources without the scope of an identified parent resource: `/users/batch/` instead of `/users/1/batch/`, obviously the latter does not really make sense in our case. It may be that this is an indicator for "transforming the subresource to a top level resource".

**Comment by lotzk** [comment]
The problem I see is that we consider `/batch/` itself somehow as resource, when it's not. It's actually a function we call in an RPC manner. 

The [HTTP specification](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) states that

> the POST method is used to request that the origin server accept **the entity enclosed in the request** as a new **subordinate** of the resource identified by the Request-URI in the Request-Line.

That is not the case for the batch requests since

- the request body just contains meta data specifying the actual resources to create
- the created resources are not subordinate to the resource identified by the Request-URI (i.e. `/batch`/) but reside somewhere else.

However, I can't come up with an idea on how to improve this witout having the frontend to dispatch multiple requests. But for now I think your are right that having `/batch/` as a top level resource is much more coherent as currently it is.

**Comment by Alexander-Krause** [comment]
The idea behind the `BatchRequestModel` was exactly to provide a RESTful resource instead of a RPC-alike function-as-a-endpoint, at least that was what we discussed back in the day. But with your explanation now, I also think that we failed with this one. 

I think that the only reasonable solution is that the frontend must fire those multiple requests and handle their return in the same fashion as currently implemented.

**Comment by lotzk** [comment]
While refactoring the routes for settings and preferences, I found another minor issue within the API for user preferences.

In general, preferences are exposed at the `/preferences/` endpoint.
FOr example, to fetch all preferences of all users, a GET request to `/preferences/ ` has to be performed. 

Since fetching preferences of all users is a rather unusual scenario, we added another endpoint to fetch only the preferences of a specific user, namely 
`/{uid}/preferences`. In this case, preferences are viewed at as if they are subordinate to a user, which in our data model is currently not true. 
Preferences express relationships from users to settings. They are are entities on their own and should thus be treated as such, like we do to create or update them.

I propose we refactor the URI to fetch settings of a specific user, which ultimately means only filtering the list, to `/preferences?filter[user]=<uid>`. This complies with how we filter other collections.

I guess this would involve some changes to the frontend. How do you feel about that?

**Comment by Alexander-Krause** [comment]
Sounds great, will you add this to the issue/118 branch?

**Comment by Alexander-Krause** [comment]
Merged
