### ISSUE TITLE
Gradle: Update to version 5.2

### ISSUE THREAD

**Issue by czirkelbach** [ExplorViz/explorviz-backend#49]
For the next release we should update our multiprojects and update them to be based on Gradle version 5.2. Related to https://github.com/ExplorViz/explorviz-backend-shared/issues/1.

**Comment by Alexander-Krause** [comment]
I am experiencing issues with the `compileJava` task for the latest Gradle version 5.2.1. For example, we use the dependency `user`, i.e., the subproject of our shared-multi-project, in our `authentication` service. `user` uses the dependency `xyz.morphia.morphia` and `authentication` uses the same dependency. 

Prior to 5.2.1 this was no problem since Gradle used the transitive dependency, i.e.,

authentication -> user -> morphia => authentication -> morphia.

I can see that this dependency is in fact downloaded and used in Eclipse, but not for the `gradle compileJava` task. Therefore, Eclipse does not show any error, but the gradle build fails.

I created a new branch `gradle-update` so that @czirkelbach and @lotzk can verify if they have the same problem.

**Comment by Alexander-Krause** [comment]
Fixed with https://github.com/ExplorViz/explorviz-backend-shared/commit/522ef24743ee8bb246b8b82e80305ac047205e30
